In [3]:
import pandas as pd
import json

# Match Summary

In [4]:
# opening the csv file
with open("t20_wc_match_results.json") as f:
    data = json.load(f)

df_summary = pd.DataFrame(data[0]['matchSummary'])

In [5]:
df_summary.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [6]:
df_summary.rename({"scorecard":"match_id"} , inplace=True , axis=1)

In [7]:
df_summary.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [8]:
df_summary.to_csv("fact_results_summary.csv" , index = False)

In [9]:
match_ids_dict={}

for index, row in df_summary.iterrows():
    key1 = row['team1'] + " Vs " + row['team2']
    key2 = row['team2'] + " Vs " + row['team1']
    
    match_ids_dict[key1] = row["match_id"]
    match_ids_dict[key2] = row["match_id"]

match_ids_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

# Batting Summary

In [10]:
with open ("t20_wc_batting_summary.json") as f:
    data = json.load(f)
    
all_records=[]
for rec in data:
    all_records.extend(rec["battingSummary"])
    
df_batting = pd.DataFrame(all_records)
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00

In [11]:
df_batting["Out/not Out"] = df_batting.dismissal.apply(lambda x : "out" if len(x) > 0 else "Not Out")
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,Out/not Out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,Not Out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00,out

In [12]:
df_batting["batsmanName"] = df_batting["batsmanName"].apply(lambda x : x.replace("â€",""))
df_batting["batsmanName"] = df_batting["batsmanName"].apply(lambda x : x.replace("\xa0",""))
df_batting["dismissal"] = df_batting["dismissal"].apply(lambda x : x.replace("â€",""))
df_batting["dismissal"] = df_batting["dismissal"].apply(lambda x : x.replace("\xa0",""))
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,Out/not Out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/Mendis),44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c Mendis b Theekshana,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75,Not Out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,c Green b Wiese,6,6,0,0,100.00,out

In [13]:
df_batting["match_id"] = df_batting["match"].map(match_ids_dict)

In [14]:
df_batting

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,Out/not Out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c Mendis b Karunaratne,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...,...
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11,out,T20I # 1879
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12,Not Out,T20I # 1879
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95,out,T20I # 1879
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15,out,T20I # 1879
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00,Not Out,T20I # 1879

In [15]:
df_batting.to_csv("fact_summary.csv", index  = False)

# Bowling Summary

In [16]:
with open("t20_wc_bowling_summary.json") as f:
    data = json.load(f)
    
records_data=[]
for rec in data:
    records_data.extend(rec["bowlingSummary"])
    
df_bowling = pd.DataFrame(records_data)

In [17]:
df_bowling.head(10)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0
5,Namibia Vs Sri Lanka,Namibia,Gerhard Erasmus,1,0,8,0,8.00,1,1,0,0,0
6,Namibia Vs Sri Lanka,Namibia,David Wiese,4,0,16,2,4.00,13,1,0,0,0
7,Namibia Vs Sri Lanka,Namibia,Bernard Scholtz,4,0,18,2,4.50,10,1,0,0,0
8,Namibia Vs Sri Lanka,Namibia,Ben Shikongo,3,1,22,2,7.33,6,3,0,0,0
9,Namibia Vs Sri Lanka,Namibia,JJ Smit,3,0,16,1,5.33,7,0,0,1,0

In [18]:
df_bowling["match_id"] = df_bowling["match"].map(match_ids_dict)

In [32]:
df_bowling["bowlerName"] = df_bowling["bowlerName"].apply(lambda x : x.replace("â€",""))
df_bowling["bowlerName"] = df_bowling["bowlerName"].apply(lambda x : x.replace("\xa0",""))

In [33]:
df_bowling

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Pakistan Vs England,Pakistan,Naseem Shah,4,0,30,0,7.50,15,3,1,1,0,T20I # 1879
496,Pakistan Vs England,Pakistan,Haris Rauf,4,0,23,2,5.75,13,3,0,1,0,T20I # 1879
497,Pakistan Vs England,Pakistan,Shadab Khan,4,0,20,1,5.00,10,1,0,0,0,T20I # 1879
498,Pakistan Vs England,Pakistan,Mohammad Wasim,4,0,38,1,9.50,5,5,0,2,0,T20I # 1879
499,Pakistan Vs England,Pakistan,Iftikhar Ahmed,0.5,0,13,0,15.60,0,1,1,0,0,T20I # 1879

In [34]:
df_bowling.to_csv("fact_bowling_summary.csv" , index = False)

# Player Information

In [20]:
with open("t20_wc_player_info.json") as f:
    data = json.load(f)

In [21]:
df_info = pd.DataFrame(data)

In [22]:
df_info

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
...,...,...,...,...,...,...
214,Tabraiz Shamsi,South Africa,Right hand Bat,Left arm Wrist spin,Bowler,A left-arm wristspin bowler with ample variati...
215,Phil Salt,England,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Phil Salt's fearless ball-striking at the top ...
216,Chris Jordan,England,Right hand Bat,Right arm Fast medium,Bowler,"Chris Jordan, a fast bowler with a level-heade..."
217,Regis Chakabva(c)â€,Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
218,Mehidy Hasan Miraz,Bangladesh,Right hand Bat,Right arm Offbreak,Allrounder,Mehedi Hasan Miraz has emerged as one of the b...

In [23]:
df_info[ (df_info["playingRole"]=="Bowler")].head(30)

,name,team,battingStyle,bowlingStyle,playingRole,description
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
20,Bernard Scholtz,Namibia,Right hand Bat,Slow Left arm Orthodox,Bowler,Bernard Scholtz's brother Nicolaas is currentl...
21,Ben Shikongo,Namibia,Right hand Bat,Right arm Medium fast,Bowler,
28,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,A tall and accurate fast bowler who is unrelen...
29,Pat Cummins,Australia,Right hand Bat,Right arm Fast,Bowler,Earmarked as a potential star from a young age...
30,Mitchell Starc,Australia,Left hand Bat,Left arm Fast,Bowler,"First there was Johnson, then there was Starc...."
31,Ashton Agar,Australia,Left hand Bat,Slow Left arm Orthodox,Bowler,Ashton Agar initially turned almost as many he...
32,Binura Fernando,Sri Lanka,Right hand Bat,Left arm Medium fast,Bowler,Known for his ability to generate awkward boun...
33,Lahiru Kumara,Sri Lanka,Left hand Bat,Right arm Fast,Bowler,"A robust, right-arm fast bowler from Kandy, La..."
42,Luke Jongwe,Zimbabwe,Right hand Bat,Right arm Fast medium,Bowler,
52,Barry McCarthy,Ireland,Right hand Bat,Right arm Fast medium,Bowler,Barry McCarthy is an Ireland seam bowler whose...
53,Josh Little,Ireland,Right hand Bat,Left arm Fast medium,Bowler,"A bustling left-arm seamer from Dublin, Josh L..."
54,Richard Ngarava,Zimbabwe,Left hand Bat,Left arm Fast medium,Bowler,
55,Tendai Chatara,Zimbabwe,Right hand Bat,Right arm Fast medium,Bowler,The first thing one notices when watching Tend...
56,Blessing Muzarabani,Zimbabwe,Right hand Bat,Right arm Fast medium,Bowler,
65,Mujeeb Ur Rahman,Afghanistan,Right hand Bat,Right arm Offbreak,Bowler,He can bowl traditional offspin and mix it up ...
66,Fareed Ahmad,Afghanistan,Left hand Bat,Left arm Fast medium,Bowler,
67,Fazalhaq Farooqi,Afghanistan,Right hand Bat,Left arm Fast medium,Bowler,
76,Mark Wood,England,Right hand Bat,Right arm Fast,Bowler,"It looked, for a while, as if Mark Wood would ..."
78,Adil Rashid,England,Right hand Bat,Legbreak,Bowler,Adil Rashid did much to set right English cric...
86,Ruben Trumpelmann,Namibia,Right hand Bat,Left arm Fast,Bowler,
87,Junaid Siddique,U.A.E.,Right hand Bat,Right arm Medium fast,Bowler,
88,Zahoor Khan,U.A.E.,Right hand Bat,Right arm Medium fast,Bowler,
89,Ahmed Raza,U.A.E.,Right hand Bat,Slow Left arm Orthodox,Bowler,Six-foot-five Ahmed Raza is best known for his...
90,Karthik Meiyappan,U.A.E.,Right hand Bat,Legbreak,Bowler,
94,Zawar Farid,U.A.E.,Right hand Bat,Right arm Medium,Bowler,
103,Logan van Beek,Netherlands,Right hand Bat,Right arm Medium fast,Bowler,Logan van Beek is an allrounder in more ways t...
104,Fred Klaassen,Netherlands,Right hand Bat,Left arm Fast medium,Bowler,Spotted as part of a Netherlands development s...

In [24]:
df_info["name"] = df_info["name"].apply(lambda x : x.replace("â€",""))
df_info["name"] = df_info["name"].apply(lambda x : x.replace("\xa0",""))

In [31]:
df_info[(df_info["playingRole"]=="Wicketkeeper Batter")].head(30)

,name,team,battingStyle,bowlingStyle,playingRole,description
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
35,Regis Chakabva,Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
45,Lorcan Tucker,Ireland,Right hand Bat,,Wicketkeeper Batter,
58,Rahmanullah Gurbaz,Afghanistan,Right hand Bat,,Wicketkeeper Batter,
68,Jos Buttler(c),England,Right hand Bat,,Wicketkeeper Batter,England have had many players down the ages wh...
85,Zane Green,Namibia,Left hand Bat,,Wicketkeeper Batter,
100,Scott Edwards(c),Netherlands,Right hand Bat,,Wicketkeeper Batter,
107,Johnson Charles,West Indies,Right hand Bat,,Wicketkeeper Batter,A muscular opener with a penchant for swatting...
110,Nicholas Pooran(c),West Indies,Left hand Bat,Right arm Offbreak,Wicketkeeper Batter,Nicholas Pooran confirmed his status as one of...
117,Mohammad Rizwan,Pakistan,Right hand Bat,,Wicketkeeper Batter,"For several years, it appeared Mohammad Rizwan..."
133,Dinesh Karthik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
141,Litton Das,Bangladesh,Right hand Bat,,Wicketkeeper Batter,Liton Das is the first wicketkeeper-batsman in...
145,Nurul Hasan,Bangladesh,Right hand Bat,,Wicketkeeper Batter,"Nurul Hasan, who made his first-class debut in..."
155,Matthew Cross,Scotland,Right hand Bat,,Wicketkeeper Batter,"A wicketkeeper-batter from Aberdeen, Matthew C..."
165,Quinton de Kock,South Africa,Left hand Bat,,Wicketkeeper Batter,Quinton de Kock's fearless striking and handy ...
174,Devon Conway,New Zealand,Left hand Bat,Right arm Medium,Wicketkeeper Batter,
176,Glenn Phillips,New Zealand,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Glenn Phillips is a top-order wicketkeeper-bat...
179,Matthew Wade,Australia,Left hand Bat,Right arm Medium,Wicketkeeper Batter,It has been a career of reinvention for Matthe...
196,Tristan Stubbs,South Africa,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,
201,Heinrich Klaasen,South Africa,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A clean-hitting, wicketkeeper batsman, Heinric..."
206,Matthew Wade(c),Australia,Left hand Bat,Right arm Medium,Wicketkeeper Batter,It has been a career of reinvention for Matthe...
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."
215,Phil Salt,England,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Phil Salt's fearless ball-striking at the top ...
217,Regis Chakabva(c),Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."

In [35]:
df_info.to_csv("fact_info_summary.csv" , index = False)